#!/usr/bin/env python3
"""Renders one view per door from the federated register into views/: a Markdown page per door,
and per world a JSON file with each concept's links into the other worlds (views/<world>.json),
which the Starlight theme (packages/starlight-theme) shows in each site's glossary."""
import json
from terms_lib import load, lang, aslist, ROOT
REL = {"de": {"skos:exactMatch":"gleich","skos:closeMatch":"nahezu gleich","skos:relatedMatch":"verwandt","skos:narrowMatch":"allgemeiner als","skos:broadMatch":"spezieller als","rl:falseFriend":"falscher Freund","rl:convergesWith":"Ziel: gleich mit"},
       "en": {"skos:exactMatch":"same","skos:closeMatch":"close","skos:relatedMatch":"related","skos:narrowMatch":"broader than","skos:broadMatch":"narrower than","rl:falseFriend":"false friend","rl:convergesWith":"target: same as"}}
WORLD = {"de": {"rlnp":"Netzwerk","rltp":"Protokoll","rls":"Stack"}, "en": {"rlnp":"Network","rltp":"Protocol","rls":"Stack"}}
PAGE = {"rlnp":"network.md","rltp":"trust.md","rls":"stack.md"}; PRIMARY = {"rlnp":"de","rltp":"en","rls":"de"}

def heading_anchor(label): return (label or "").lower().replace(" ", "-")

def glossary_url(concept, glossary, l):
    """Address of a concept's entry in its world's glossary: by local name, or by heading where the
    glossary is a rendered view (sources.json: "anchor": "heading")."""
    w = concept["_world"]
    anchor = heading_anchor(lang(concept["skos:prefLabel"], PRIMARY[w])) if glossary.get("anchor") == "heading" else concept["@id"].split(":", 1)[1]
    return f"{glossary.get(l) or glossary['en']}#{anchor}"

def world_json(world, concepts, links, sources):
    """{"world", "concepts": {local name: [{relation, world, id, label{de,en}, url{de,en}}]}}, links seen from the concept."""
    out = {"world": world, "concepts": {}}
    for cid in sorted(c for c in concepts if concepts[c]["_world"] == world):
        entries = []
        for rel, b in links.get(cid, []):
            o = concepts[b]; g = sources[o["_world"]]["glossary"]
            entries.append({"relation": rel.split(":", 1)[1], "world": o["_world"], "id": b,
                            "label": {l: lang(o["skos:prefLabel"], l) for l in ("de", "en")},
                            "url": {l: glossary_url(o, g, l) for l in ("de", "en")}})
        if entries: out["concepts"][cid.split(":", 1)[1]] = entries
    return out

def render(world, langs, show_iri, show_sym, title, out):
    L = [f"# {title}", "", "*Generated by scripts/render.py. Do not edit.*", ""]
    for c in sorted(concepts.values(), key=lambda c: (lang(c["skos:prefLabel"], langs[0]) or "")):
        if c["_world"] != world: continue
        l0 = langs[0]
        L.append(f"## {lang(c['skos:prefLabel'], l0)}")
        for l in langs[1:]: L.append(f"*{lang(c['skos:prefLabel'], l)}*")
        if show_iri: L.append(f"`{c['@id']}`")
        if c.get("rl:status") == "proposed": L.append("**" + ("Vorschlag, noch nicht in der Spec" if l0 == "de" else "Proposal, not yet in the spec") + "**")
        for l in langs: L += ["", lang(c["skos:definition"], l)]
        alts = [a["@value"] for a in aslist(c.get("skos:altLabel", []))]
        if alts: L += ["", ("Auch: " if l0 == "de" else "Also: ") + ", ".join(alts)]
        if show_sym and c.get("rl:symbol"): L += ["", "Code: " + ", ".join(f"`{s}`" for s in c["rl:symbol"])]
        L += ["", ("Quelle: " if l0 == "de" else "Source: ") + ", ".join(f"[{u.rsplit('/',1)[-1]}]({u})" for u in aslist(c["dct:source"]))]
        if links[c["@id"]]:
            L.append("")
            for rel, b in links[c["@id"]]:
                o = concepts[b]; anchor = heading_anchor(lang(o["skos:prefLabel"], PRIMARY[o["_world"]]))
                tgt = f"[{lang(o['skos:prefLabel'], l0) or b}]({PAGE[o['_world']]}#{anchor})" + (f" `{b}`" if show_iri else "")
                L.append(f"- {REL[l0][rel]}: **{tgt}** ({WORLD[l0][o['_world']]})")
        for n in notes.get(c["@id"], []): L += ["", f"> {n}"]
        L.append("")
    (ROOT / "views" / out).write_text("\n".join(L))

if __name__ == "__main__":
    concepts, links, notes, problems, warnings = load()
    if problems: raise SystemExit("register has errors; run guard.py first")
    render("rlnp", ["de", "en"], False, False, "Begriffe · reallife.network", "network.md")
    render("rltp", ["en", "de"], True, False, "Terms · trust-protocol.real-life.org", "trust.md")
    render("rls", ["de", "en"], False, True, "Begriffe · real-life-stack.de", "stack.md")
    sources = json.load(open(ROOT / "terms/sources.json"))["schemes"]
    for w in sources:
        (ROOT / "views" / f"{w}.json").write_text(json.dumps(world_json(w, concepts, links, sources), indent=1, ensure_ascii=False) + "\n")
    print("views written")
